clean: true
objc: false
readme: Readme.md
framework_root: MBAdmin
module_version: 1.0
sdk: iphonesimulator

xcodebuild_arguments:
    - "-workspace"
    - "MBAdmin.xcworkspace"
    - "-scheme"
    - "MBAdmin"

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/MBAdmin

theme: fullwidth

custom_categories:

  - name: MBAdmin
    children:
    - MBAdmin
  - name: MBUplodableElementFactory
    children:
    - MBUploadableElementsFactory
  - name: MBUplodableElements
    children:
    - MBUplodableElementProtocol
    - MBUploadableCheckboxElement
    - MBUploadableFilesElement
    - MBUploadableImagesElement
    - MBUploadableTextElement
    - MBUploadableColorElement
    - MBUploadableRelationElement
